/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_android_jni_Decodec */

#ifndef _Included_com_android_jni_Decodec
#define _Included_com_android_jni_Decodec
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_android_jni_Decodec
 * Method:    newdecode
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_android_jni_Decodec_newdecode
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
